spring.profiles.active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://mysql:3306/ebook_chat?useSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    store-type: redis  
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0
  redis:
    host: redis
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

flyway.enabled: true      
security.headers.cache: false 
server.session.timeout: 600

ebook:
  chat:
    relay:
      host: rabbitmq
      port: 61613

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://mysql:3306/ebook_chat?useSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

flyway.enabled: true

ebook:
  chat:
    relay:
      host: rabbitmq
      port: 61613